import http from 'node:http';

export async function startFixture() {
  const html = `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pedidos — aplicación de prueba</title><style>body{margin:0;font-family:system-ui;background:#f4f6f8;color:#182436}header{padding:20px 32px;background:#182436;color:white;display:flex;justify-content:space-between;align-items:center}main{max-width:1100px;margin:40px auto;padding:0 24px}.wide{min-width:820px}.cards{display:flex;gap:20px}.card{padding:24px;background:white;border:1px solid #d9e0e8;flex:1}.number{font-size:36px}button{font:inherit;background:#254e82;color:white;border:0;padding:12px 18px;cursor:pointer}h1{font-size:32px}section{margin-top:24px;padding:24px;background:white}input{display:block;font:inherit;padding:10px;margin:8px 0 20px;border:1px solid #8a96a6;width:300px}.muted{color:#a9b0b8;font-size:13px}#error{color:#a32730}table{width:100%;text-align:left;border-collapse:collapse}td,th{padding:15px;border-bottom:1px solid #ddd}</style></head><body><header><strong>Pedidos / Demo</strong><button id="open-settings">Configuración</button></header><main class="wide"><h1>Resumen de pedidos</h1><p>Aplicación de prueba con problemas intencionales de accesibilidad y adaptación.</p><div class="cards"><div class="card"><div class="number">24</div>Pedidos pendientes</div><div class="card"><div class="number">8</div>Listos para entregar</div><div class="card"><div class="number">92%</div>Entregas a tiempo</div></div><section><h2>Pedidos recientes</h2><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Estado</th></tr></thead><tbody><tr><td>DEMO-104</td><td>Cliente de prueba</td><td>Pendiente</td></tr><tr><td>DEMO-103</td><td>Cliente de prueba</td><td>En preparación</td></tr></tbody></table><p class="muted">Última actualización hace 5 minutos.</p></section><section id="settings" hidden><h2>Configuración de notificaciones</h2><form id="form" novalidate><span>Correo de contacto</span><input id="email" type="email"><button id="save" type="submit">Guardar cambios</button><p id="error" hidden></p></form></section></main><script>document.getElementById('open-settings').onclick=()=>{document.getElementById('settings').hidden=false};document.getElementById('form').onsubmit=event=>{event.preventDefault();const error=document.getElementById('error');error.hidden=false;error.textContent=document.getElementById('email').value.includes('@')?'Cambios guardados':'Revisa el correo de contacto.'}</script></body></html>`;
  const server = http.createServer((request, response) => {
    if (request.url === '/favicon.ico') { response.writeHead(204); response.end(); return; }
    response.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Content-Security-Policy': "default-src 'self'; script-src 'nonce-fixture'; style-src 'unsafe-inline'" });
    response.end(html.replace('<script>', '<script nonce="fixture">'));
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  return { url: `http://127.0.0.1:${server.address().port}`, close: () => new Promise(resolve => server.close(resolve)) };
}
